version: '3.8'

services:
  router1:
    image: azizhalq/smartnet:router-latest
    container_name: router1
    environment:
      - ROUTER_ID=router1
    networks:
      - dds-net

  router2:
    image: azizhalq/smartnet:router-latest
    container_name: router2
    environment:
      - ROUTER_ID=router2
    networks:
      - dds-net

  router3:
    image: azizhalq/smartnet:router-latest
    container_name: router3
    environment:
      - ROUTER_ID=router3
    networks:
      - dds-net

  dashboard:
    image: azizhalq/smartnet:dashboard-latest
    container_name: dashboard
    ports:
      - "5000:5000"  # Expose port for Flask web app
    networks:
      - dds-net

networks:
  dds-net:
    driver: bridge
